flowchart TD
    A[Wartości liczbowe] --> B[Operatory arytmetyczne]
    B --> C[Nowa wartość liczbowa]
    C --> D[Porównanie]
    D --> E[bool]
    E --> F[Operatory logiczne]
    F --> G[Warunek programu]