flowchart TD
    A[Inicjalizacja] --> B[int[]]
    A --> C[int[,]]
    A --> D[int[][]]
    B --> E[Length]
    C --> F[GetLength 0 i 1]
    D --> G[Length wiersza]
    F --> H[Zagnieżdżone pętle]
    G --> H
