flowchart TD
    A[Algorytmy rekurencyjne] --> B[Silnia]
    A --> C[NWD]
    A --> D[Wyszukiwanie binarne]
    A --> E[Drzewo binarne]
    B --> F[Zmniejsz n]
    C --> G[Reszta z dzielenia]
    D --> H[Odrzuc polowe]
    E --> I[Lewe i prawe poddrzewo]