mindmap
  root((Algorytm))
    Dane wejściowe
      wartości
      ograniczenia
      przypadki brzegowe
    Kroki
      jednoznaczne
      wykonalne
      uporządkowane
    Wynik
      określony
      sprawdzalny
    Zakończenie
      skończona liczba kroków
      warunek stopu